# Necessary stuff.
base_url = "http://127.0.0.1:1111"
title = "~/tabi"
description = "tabi is a simple personal site and blogging theme for Zola."
generate_feed = true
compile_sass = true
minify_html = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "css"

[extra]
# Date format used when listing posts (main page, /blog section, tag posts list…)
# Default is "6th July 2049".
long_date_format = "%d %B %Y"

# Date format used for blog posts.
# Default is "31st Dec 2011".
short_date_format = ""

# Custom separator used in title tag and posts metadata (between date, time to read, and tags).
separator = "•"

# Full path after the base URL required. So if you were to place it in "static" it would be "/favicon.ico"
favicon = ""

# This header image is used for SEO. For example if you were to share an image via Messenger/Instagram/Twitter a preview picture is also presented
headerImage = ""

# The icon is display besides the menu text but is not necessary. It needs to be placed under "menu_icon" in the static "folder"
menu = [
    { name = "blog", url = "$BASE_URL/blog" },
    { name = "archive", url = "$BASE_URL/archive" },
    { name = "tags", url = "$BASE_URL/tags" },
    { name = "projects", url = "$BASE_URL/projects" },
]

#The icons available can be found in "social_icons" in the "static" folder
socials = [
    { name = "atom feed", url = "$BASE_URL/atom.xml", icon = "rss" },
    { name = "github", url = "https://github.com/welpo/", icon = "github" },
    { name = "soundcloud", url = "https://soundcloud.com/oskerwyld", icon = "soundcloud" },
    { name = "instagram", url = "https://instagram.com/oskerwyld", icon = "instagram" },
    { name = "youtube", url = "https://youtube.com/@oskerwyld", icon = "youtube" },
    { name = "spotify", url = "https://open.spotify.com/artist/5Hv2bYBhMp1lUHFri06xkE", icon = "spotify" },
]

# Custom security headers. What urls should your website be able to connect to?
# You need to specify the CSP and the URLs associated with the directive.
# Useful if you want to load remote content safely (embed YouTube videos, which needs frame-src, for example).
# Default directive is self.
# Default config, allows for https remote images and embedding YouTube and Vimeo content.
# This configuration gets an A+ in Mozilla's Observatory: https://observatory.mozilla.org
allowed_domains = [
    { directive = "img-src", domains = ["'self'", "https://*"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'"] },
    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
]
